### ISSUE TITLE
Extend container service Gem with health and ready endpoints

### ISSUE THREAD

**Issue by cseifert-betterdoc** [betterdoc-org/general-gem-betterdoc-containerservice#24]
## Context

Kubernetes defined *ready* and *healthy* endpoints (see https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/).

Our container service gem should provide a default implementation of these endpoints that can - if needed - be overwritten by the actual services.

**Comment by sebastian-schuth** [comment]
From the k8s page:

> Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.

I plan to add an endpoint that sends a plain `400 BAD REQUEST` in case the service is reachable  and wants to communicate that it is not ready or health.

Plan is to make this part of the metadata endpoint, so the heath endpoint is planned to be accessible under:

`__META__/health`

and the ready endpoint:

`__META__/ready`

Current thinking is that the ready endpoint will as default return whatever the health endpoint responds. This way, if a custom heath endpoint is added, the ready endpoint will be consistent with it.

Support for a custom health and ready endpoint is also planned. The default implementation will rely on the fact that we consider a rails app to be healthy as soon as the controller can be called via http.

Maybe too detailed, but still in my head: we may be able to hook into some rails events fired on start-up to provide an even finer-grained default readiness definition, but I am not sure if this is worth the hassle and the complexity.

**Comment by sebastian-schuth** [comment]
The implementation will reside in a new Gem, which will then be required by the betterdoc-containerservice gem.

https://github.com/betterdoc-org/infrastructure-gem-runtime_info

**Comment by sebastian-schuth** [comment]
@cseifert-betterdoc please have a look at the impl at https://github.com/betterdoc-org/infrastructure-gem-runtime_info -- this is the initial version, so no PR in that repository yet.

Would be great to discuss the changes.

**Comment by sebastian-schuth** [comment]
Current status: github packages seems to have some kind of bug (or a pitfall when configuring access to it) -- I am waiting for GH support to tell me what is going on.

**Comment by sebastian-schuth** [comment]
Following parts have been touched to get this up and running:

- a new gem was created: https://github.com/betterdoc-org/infrastructure-gem-runtimeinfo
-- the gem is pushed to github packages 
- the CircleCi orbs for building heroku and building and pushing Dockerfiles to Heroku and our k8s cluster are updated to be able to pass the credentials needed to access our private github packages repo with the needed gem
-- the needed credentials have been added to some circleCi context in order to make them usable in CI builds https://circleci.com/gh/organizations/betterdoc-org/settings#contexts

The readme of https://github.com/betterdoc-org/infrastructure-gem-runtimeinfo gives some overview of what the new GEM adds.

However, the new GEM is **not** added as dependency to the container service gem -- adding it as dependency is not feasible, as this would mean all needed changes need to be rolled out to all rails apps using the container service gem.

So, this is somewhat more complicated than needed, but it was worth the effort as it forced us to do the steps we need to get private gems into our setup.
